# Site settings
title: Garcia Lab
description: > 
    Physical Biology of the Embryo
baseurl: "/" # the subpath of your site, e.g. /blog/

# Build settings
markdown: kramdown
paginate: 3
paginate_path: "blog/page:num"

# Lab location information for contact us page
contact:
    text: >
      We are very excited to hear from people that share our
      interests in developmental biology and the quantitative study
      of living matter. Students and postdocs interested in joining
      the lab should contact Prof. Garcia directly. <br/><br/>
      Prospective graduate students can also find more information
      about the <a href="http://mcb.berkeley.edu">Department of Molecular & Cell Biology</a>, research on
      <a href="http://www.drbberkeley.org/">Developmental and Regenerative
      Biology</a>, the <a href="http://physics.berkeley.edu/">Department of
      Physics</a> and the <a href="http://biophysics.berkeley.edu/">Biophysics Graduate Program at their respective
      websites</a>. 
      <br/><br/>
    address: > 
      Garcia Lab 505<br/>
      142 Weill Hall (formerly Life Sciences Addition), #3200<br/>
      University of California at Berkeley<br/>
      Berkeley, CA 94720-3200<br/>
    email: "hggarcia@berkeley.edu"
    phone: 510-664-7847

plugins: [jekyll-paginate, jekyll]

